export interface AssetEntry {
  symbol: string
  name: string
  category: string
}

export const ASSET_DATABASE: AssetEntry[] = [
  // ─── Forex – Majors ───────────────────────────────────────────────────────
  { symbol: 'EURUSD', name: 'Euro / US Dollar',               category: 'forex' },
  { symbol: 'GBPUSD', name: 'British Pound / US Dollar',      category: 'forex' },
  { symbol: 'USDJPY', name: 'US Dollar / Japanese Yen',       category: 'forex' },
  { symbol: 'USDCHF', name: 'US Dollar / Swiss Franc',        category: 'forex' },
  { symbol: 'AUDUSD', name: 'Australian Dollar / USD',        category: 'forex' },
  { symbol: 'NZDUSD', name: 'New Zealand Dollar / USD',       category: 'forex' },
  { symbol: 'USDCAD', name: 'US Dollar / Canadian Dollar',    category: 'forex' },
  // ─── Forex – Crosses ─────────────────────────────────────────────────────
  { symbol: 'EURGBP', name: 'Euro / British Pound',           category: 'forex' },
  { symbol: 'EURJPY', name: 'Euro / Japanese Yen',            category: 'forex' },
  { symbol: 'EURCHF', name: 'Euro / Swiss Franc',             category: 'forex' },
  { symbol: 'EURAUD', name: 'Euro / Australian Dollar',       category: 'forex' },
  { symbol: 'EURCAD', name: 'Euro / Canadian Dollar',         category: 'forex' },
  { symbol: 'EURNZD', name: 'Euro / New Zealand Dollar',      category: 'forex' },
  { symbol: 'GBPJPY', name: 'British Pound / Japanese Yen',  category: 'forex' },
  { symbol: 'GBPCHF', name: 'British Pound / Swiss Franc',   category: 'forex' },
  { symbol: 'GBPAUD', name: 'British Pound / Australian $',  category: 'forex' },
  { symbol: 'GBPCAD', name: 'British Pound / Canadian $',    category: 'forex' },
  { symbol: 'GBPNZD', name: 'British Pound / New Zealand $', category: 'forex' },
  { symbol: 'AUDJPY', name: 'Australian Dollar / Yen',        category: 'forex' },
  { symbol: 'AUDCHF', name: 'Australian Dollar / Franc',      category: 'forex' },
  { symbol: 'AUDCAD', name: 'Australian Dollar / Canadian $', category: 'forex' },
  { symbol: 'AUDNZD', name: 'Australian Dollar / NZD',        category: 'forex' },
  { symbol: 'NZDJPY', name: 'New Zealand Dollar / Yen',       category: 'forex' },
  { symbol: 'NZDCHF', name: 'New Zealand Dollar / Franc',     category: 'forex' },
  { symbol: 'NZDCAD', name: 'New Zealand Dollar / CAD',       category: 'forex' },
  { symbol: 'CADJPY', name: 'Canadian Dollar / Yen',          category: 'forex' },
  { symbol: 'CADCHF', name: 'Canadian Dollar / Franc',        category: 'forex' },
  { symbol: 'CHFJPY', name: 'Swiss Franc / Japanese Yen',     category: 'forex' },
  // ─── Forex – Exotic ───────────────────────────────────────────────────────
  { symbol: 'USDMXN', name: 'US Dollar / Mexican Peso',       category: 'forex' },
  { symbol: 'USDZAR', name: 'US Dollar / South African Rand', category: 'forex' },
  { symbol: 'USDSEK', name: 'US Dollar / Swedish Krona',      category: 'forex' },
  { symbol: 'USDNOK', name: 'US Dollar / Norwegian Krone',    category: 'forex' },
  { symbol: 'USDDKK', name: 'US Dollar / Danish Krone',       category: 'forex' },
  { symbol: 'USDPLN', name: 'US Dollar / Polish Zloty',       category: 'forex' },
  { symbol: 'USDHUF', name: 'US Dollar / Hungarian Forint',   category: 'forex' },
  { symbol: 'USDCZK', name: 'US Dollar / Czech Koruna',       category: 'forex' },
  { symbol: 'USDSGI', name: 'US Dollar / Singapore Dollar',   category: 'forex' },
  { symbol: 'USDSGD', name: 'US Dollar / Singapore Dollar',   category: 'forex' },
  { symbol: 'USDHKD', name: 'US Dollar / Hong Kong Dollar',   category: 'forex' },
  { symbol: 'USDCNH', name: 'US Dollar / Chinese Yuan Offshore', category: 'forex' },
  { symbol: 'USDTRY', name: 'US Dollar / Turkish Lira',       category: 'forex' },
  { symbol: 'USDBRL', name: 'US Dollar / Brazilian Real',     category: 'forex' },
  { symbol: 'EURPLN', name: 'Euro / Polish Zloty',            category: 'forex' },
  { symbol: 'EURSEK', name: 'Euro / Swedish Krona',           category: 'forex' },
  { symbol: 'EURNOK', name: 'Euro / Norwegian Krone',         category: 'forex' },
  { symbol: 'EURTRY', name: 'Euro / Turkish Lira',            category: 'forex' },
  { symbol: 'EURHUF', name: 'Euro / Hungarian Forint',        category: 'forex' },
  { symbol: 'EURCZK', name: 'Euro / Czech Koruna',            category: 'forex' },
  { symbol: 'EURMXN', name: 'Euro / Mexican Peso',            category: 'forex' },
  { symbol: 'GBPSEK', name: 'British Pound / Swedish Krona',  category: 'forex' },
  { symbol: 'GBPNOK', name: 'British Pound / Norwegian Krone',category: 'forex' },
  { symbol: 'GBPPLN', name: 'British Pound / Polish Zloty',   category: 'forex' },

  // ─── Crypto ───────────────────────────────────────────────────────────────
  { symbol: 'BTC/USD',  name: 'Bitcoin / US Dollar',          category: 'crypto' },
  { symbol: 'ETH/USD',  name: 'Ethereum / US Dollar',         category: 'crypto' },
  { symbol: 'SOL/USD',  name: 'Solana / US Dollar',           category: 'crypto' },
  { symbol: 'XRP/USD',  name: 'Ripple / US Dollar',           category: 'crypto' },
  { symbol: 'BNB/USD',  name: 'BNB / US Dollar',              category: 'crypto' },
  { symbol: 'DOGE/USD', name: 'Dogecoin / US Dollar',         category: 'crypto' },
  { symbol: 'ADA/USD',  name: 'Cardano / US Dollar',          category: 'crypto' },
  { symbol: 'AVAX/USD', name: 'Avalanche / US Dollar',        category: 'crypto' },
  { symbol: 'LINK/USD', name: 'Chainlink / US Dollar',        category: 'crypto' },
  { symbol: 'DOT/USD',  name: 'Polkadot / US Dollar',         category: 'crypto' },
  { symbol: 'MATIC/USD',name: 'Polygon / US Dollar',          category: 'crypto' },
  { symbol: 'LTC/USD',  name: 'Litecoin / US Dollar',         category: 'crypto' },
  { symbol: 'NEAR/USD', name: 'NEAR Protocol / US Dollar',    category: 'crypto' },
  { symbol: 'UNI/USD',  name: 'Uniswap / US Dollar',          category: 'crypto' },
  { symbol: 'ATOM/USD', name: 'Cosmos / US Dollar',           category: 'crypto' },
  { symbol: 'SUI/USD',  name: 'Sui / US Dollar',              category: 'crypto' },
  { symbol: 'TON/USD',  name: 'Toncoin / US Dollar',          category: 'crypto' },
  { symbol: 'PEPE/USD', name: 'Pepe / US Dollar',             category: 'crypto' },
  { symbol: 'BTC/EUR',  name: 'Bitcoin / Euro',               category: 'crypto' },
  { symbol: 'ETH/EUR',  name: 'Ethereum / Euro',              category: 'crypto' },
  { symbol: 'BTCUSDT',  name: 'Bitcoin / Tether',             category: 'crypto' },
  { symbol: 'ETHUSDT',  name: 'Ethereum / Tether',            category: 'crypto' },
  { symbol: 'SOLUSDT',  name: 'Solana / Tether',              category: 'crypto' },
  { symbol: 'XRPUSDT',  name: 'Ripple / Tether',              category: 'crypto' },

  // ─── Futures – Index ──────────────────────────────────────────────────────
  { symbol: 'NQ',   name: 'E-mini Nasdaq 100 Futures',         category: 'futures' },
  { symbol: 'MNQ',  name: 'Micro E-mini Nasdaq 100',           category: 'futures' },
  { symbol: 'ES',   name: 'E-mini S&P 500 Futures',            category: 'futures' },
  { symbol: 'MES',  name: 'Micro E-mini S&P 500',              category: 'futures' },
  { symbol: 'YM',   name: 'E-mini Dow Jones Futures',          category: 'futures' },
  { symbol: 'MYM',  name: 'Micro E-mini Dow Jones',            category: 'futures' },
  { symbol: 'RTY',  name: 'E-mini Russell 2000 Futures',       category: 'futures' },
  { symbol: 'M2K',  name: 'Micro E-mini Russell 2000',         category: 'futures' },
  { symbol: 'NKD',  name: 'Nikkei 225 Dollar Futures',         category: 'futures' },
  { symbol: 'FDAX', name: 'DAX Futures (Eurex)',               category: 'futures' },
  { symbol: 'FESX', name: 'Euro Stoxx 50 Futures (Eurex)',     category: 'futures' },
  { symbol: 'FGBL', name: 'Euro Bund Futures (Eurex)',         category: 'futures' },
  { symbol: 'HSI',  name: 'Hang Seng Index Futures',           category: 'futures' },
  { symbol: 'SGXNK',name: 'SGX Nikkei 225 Futures',           category: 'futures' },

  // ─── Indices ─────────────────────────────────────────────────────────────
  { symbol: 'SPX',    name: 'S&P 500 Index',                   category: 'indices' },
  { symbol: 'NDX',    name: 'Nasdaq 100 Index',                category: 'indices' },
  { symbol: 'DJI',    name: 'Dow Jones Industrial Average',    category: 'indices' },
  { symbol: 'RUT',    name: 'Russell 2000 Index',              category: 'indices' },
  { symbol: 'DAX',    name: 'DAX Performance Index',           category: 'indices' },
  { symbol: 'FTSE',   name: 'FTSE 100 Index',                  category: 'indices' },
  { symbol: 'CAC',    name: 'CAC 40 Index',                    category: 'indices' },
  { symbol: 'N225',   name: 'Nikkei 225',                      category: 'indices' },
  { symbol: 'HSI',    name: 'Hang Seng Index',                 category: 'indices' },
  { symbol: 'IBEX',   name: 'IBEX 35 Index',                   category: 'indices' },
  { symbol: 'STOXX50',name: 'Euro Stoxx 50',                   category: 'indices' },
  { symbol: 'AEX',    name: 'AEX Index Amsterdam',             category: 'indices' },
  { symbol: 'SMI',    name: 'Swiss Market Index',              category: 'indices' },
  { symbol: 'ASX200', name: 'ASX 200 Australia',               category: 'indices' },
  { symbol: 'VIX',    name: 'CBOE Volatility Index',           category: 'indices' },

  // ─── CFD ─────────────────────────────────────────────────────────────────
  { symbol: 'DE40',   name: 'Germany 40 (DAX) CFD',           category: 'cfd' },
  { symbol: 'US100',  name: 'US 100 (Nasdaq) CFD',            category: 'cfd' },
  { symbol: 'US500',  name: 'US 500 (S&P) CFD',               category: 'cfd' },
  { symbol: 'US30',   name: 'US 30 (Dow) CFD',                category: 'cfd' },
  { symbol: 'UK100',  name: 'UK 100 (FTSE) CFD',              category: 'cfd' },
  { symbol: 'FR40',   name: 'France 40 (CAC) CFD',            category: 'cfd' },
  { symbol: 'JP225',  name: 'Japan 225 (Nikkei) CFD',         category: 'cfd' },
  { symbol: 'HK50',   name: 'Hong Kong 50 (HSI) CFD',         category: 'cfd' },
  { symbol: 'AU200',  name: 'Australia 200 (ASX) CFD',        category: 'cfd' },
  { symbol: 'EU50',   name: 'Euro Stoxx 50 CFD',              category: 'cfd' },
  { symbol: 'XAUUSD', name: 'Gold Spot CFD',                   category: 'cfd' },
  { symbol: 'XAGUSD', name: 'Silver Spot CFD',                 category: 'cfd' },
  { symbol: 'XBRUSD', name: 'Brent Crude Oil Spot CFD',        category: 'cfd' },
  { symbol: 'XTIUSD', name: 'WTI Crude Oil Spot CFD',          category: 'cfd' },

  // ─── ETF ─────────────────────────────────────────────────────────────────
  { symbol: 'SPY',    name: 'SPDR S&P 500 ETF Trust',         category: 'etf' },
  { symbol: 'QQQ',    name: 'Invesco QQQ Nasdaq ETF',         category: 'etf' },
  { symbol: 'IWM',    name: 'iShares Russell 2000 ETF',       category: 'etf' },
  { symbol: 'DIA',    name: 'SPDR Dow Jones ETF',             category: 'etf' },
  { symbol: 'GLD',    name: 'SPDR Gold Shares',               category: 'etf' },
  { symbol: 'IAU',    name: 'iShares Gold Trust',             category: 'etf' },
  { symbol: 'SLV',    name: 'iShares Silver Trust',           category: 'etf' },
  { symbol: 'TLT',    name: 'iShares 20+ Yr Treasury Bond',   category: 'etf' },
  { symbol: 'IEF',    name: 'iShares 7-10 Yr Treasury Bond',  category: 'etf' },
  { symbol: 'HYG',    name: 'iShares High Yield Corporate',   category: 'etf' },
  { symbol: 'LQD',    name: 'iShares Investment Grade Corp',  category: 'etf' },
  { symbol: 'EEM',    name: 'iShares Emerging Markets ETF',   category: 'etf' },
  { symbol: 'EFA',    name: 'iShares MSCI EAFE ETF',          category: 'etf' },
  { symbol: 'VTI',    name: 'Vanguard Total Stock Market',    category: 'etf' },
  { symbol: 'VEA',    name: 'Vanguard Developed Markets',     category: 'etf' },
  { symbol: 'VWO',    name: 'Vanguard Emerging Markets',      category: 'etf' },
  { symbol: 'XLF',    name: 'Financial Select Sector SPDR',   category: 'etf' },
  { symbol: 'XLE',    name: 'Energy Select Sector SPDR',      category: 'etf' },
  { symbol: 'XLK',    name: 'Technology Select Sector SPDR',  category: 'etf' },
  { symbol: 'XLV',    name: 'Health Care Select Sector SPDR', category: 'etf' },
  { symbol: 'ARKK',   name: 'ARK Innovation ETF',             category: 'etf' },
  { symbol: 'SQQQ',   name: 'ProShares UltraPro Short QQQ',   category: 'etf' },
  { symbol: 'TQQQ',   name: 'ProShares UltraPro QQQ',         category: 'etf' },

  // ─── Energy ──────────────────────────────────────────────────────────────
  { symbol: 'CL',     name: 'WTI Crude Oil Futures',           category: 'energy' },
  { symbol: 'MCL',    name: 'Micro WTI Crude Oil',             category: 'energy' },
  { symbol: 'BZ',     name: 'Brent Crude Oil Futures',         category: 'energy' },
  { symbol: 'NG',     name: 'Natural Gas Futures',             category: 'energy' },
  { symbol: 'RB',     name: 'RBOB Gasoline Futures',           category: 'energy' },
  { symbol: 'HO',     name: 'Heating Oil Futures',             category: 'energy' },

  // ─── Metals ──────────────────────────────────────────────────────────────
  { symbol: 'GC',     name: 'Gold Futures (COMEX)',            category: 'metals' },
  { symbol: 'MGC',    name: 'Micro Gold Futures',              category: 'metals' },
  { symbol: 'SI',     name: 'Silver Futures (COMEX)',          category: 'metals' },
  { symbol: 'SIL',    name: 'Micro Silver Futures',            category: 'metals' },
  { symbol: 'HG',     name: 'High Grade Copper Futures',       category: 'metals' },
  { symbol: 'PL',     name: 'Platinum Futures',                category: 'metals' },
  { symbol: 'PA',     name: 'Palladium Futures',               category: 'metals' },
  { symbol: 'ALI',    name: 'Aluminum Futures',                category: 'metals' },

  // ─── Agriculture ─────────────────────────────────────────────────────────
  { symbol: 'ZC',     name: 'Corn Futures (CBOT)',             category: 'agriculture' },
  { symbol: 'ZW',     name: 'Wheat Futures (CBOT)',            category: 'agriculture' },
  { symbol: 'ZS',     name: 'Soybeans Futures (CBOT)',         category: 'agriculture' },
  { symbol: 'ZL',     name: 'Soybean Oil Futures (CBOT)',      category: 'agriculture' },
  { symbol: 'ZM',     name: 'Soybean Meal Futures (CBOT)',     category: 'agriculture' },
  { symbol: 'ZO',     name: 'Oats Futures (CBOT)',             category: 'agriculture' },
  { symbol: 'ZR',     name: 'Rough Rice Futures (CBOT)',       category: 'agriculture' },
  { symbol: 'KC',     name: 'Coffee C Futures (ICE)',          category: 'agriculture' },
  { symbol: 'SB',     name: 'Sugar No. 11 Futures (ICE)',      category: 'agriculture' },
  { symbol: 'CC',     name: 'Cocoa Futures (ICE)',             category: 'agriculture' },
  { symbol: 'CT',     name: 'Cotton No. 2 Futures (ICE)',      category: 'agriculture' },
  { symbol: 'OJ',     name: 'Orange Juice Futures (ICE)',      category: 'agriculture' },
  { symbol: 'LB',     name: 'Lumber Futures (CME)',            category: 'agriculture' },
  { symbol: 'LE',     name: 'Live Cattle Futures (CME)',       category: 'agriculture' },
  { symbol: 'GF',     name: 'Feeder Cattle Futures (CME)',     category: 'agriculture' },
  { symbol: 'HE',     name: 'Lean Hogs Futures (CME)',         category: 'agriculture' },

  // ─── Bonds / Rates ───────────────────────────────────────────────────────
  { symbol: 'ZN',     name: '10-Year T-Note Futures',          category: 'bonds' },
  { symbol: 'ZB',     name: '30-Year T-Bond Futures',          category: 'bonds' },
  { symbol: 'ZF',     name: '5-Year T-Note Futures',           category: 'bonds' },
  { symbol: 'ZT',     name: '2-Year T-Note Futures',           category: 'bonds' },
  { symbol: 'UB',     name: 'Ultra T-Bond Futures',            category: 'bonds' },
  { symbol: 'GE',     name: 'Eurodollar Futures (CME)',        category: 'bonds' },
  { symbol: 'FGBL',   name: 'Euro Bund Futures (Eurex)',       category: 'bonds' },
  { symbol: 'FGBM',   name: 'Euro Bobl Futures (Eurex)',       category: 'bonds' },
  { symbol: 'FGBS',   name: 'Euro Schatz Futures (Eurex)',     category: 'bonds' },
  { symbol: 'FOAT',   name: 'OAT Futures (Eurex)',             category: 'bonds' },
  { symbol: 'FBTP',   name: 'BTP Futures (Eurex)',             category: 'bonds' },

  // ─── Aktien – US Large Caps ───────────────────────────────────────────────
  { symbol: 'AAPL',   name: 'Apple Inc.',                      category: 'stocks' },
  { symbol: 'MSFT',   name: 'Microsoft Corporation',           category: 'stocks' },
  { symbol: 'GOOGL',  name: 'Alphabet Inc. (Class A)',         category: 'stocks' },
  { symbol: 'GOOG',   name: 'Alphabet Inc. (Class C)',         category: 'stocks' },
  { symbol: 'AMZN',   name: 'Amazon.com Inc.',                 category: 'stocks' },
  { symbol: 'NVDA',   name: 'NVIDIA Corporation',              category: 'stocks' },
  { symbol: 'META',   name: 'Meta Platforms Inc.',             category: 'stocks' },
  { symbol: 'TSLA',   name: 'Tesla Inc.',                      category: 'stocks' },
  { symbol: 'BRK.B',  name: 'Berkshire Hathaway B',           category: 'stocks' },
  { symbol: 'JPM',    name: 'JPMorgan Chase & Co.',            category: 'stocks' },
  { symbol: 'V',      name: 'Visa Inc.',                       category: 'stocks' },
  { symbol: 'MA',     name: 'Mastercard Inc.',                 category: 'stocks' },
  { symbol: 'UNH',    name: 'UnitedHealth Group',              category: 'stocks' },
  { symbol: 'JNJ',    name: 'Johnson & Johnson',               category: 'stocks' },
  { symbol: 'XOM',    name: 'Exxon Mobil Corporation',         category: 'stocks' },
  { symbol: 'WMT',    name: 'Walmart Inc.',                    category: 'stocks' },
  { symbol: 'PG',     name: 'Procter & Gamble Co.',            category: 'stocks' },
  { symbol: 'HD',     name: 'The Home Depot Inc.',             category: 'stocks' },
  { symbol: 'LLY',    name: 'Eli Lilly and Company',           category: 'stocks' },
  { symbol: 'AVGO',   name: 'Broadcom Inc.',                   category: 'stocks' },
  { symbol: 'AMD',    name: 'Advanced Micro Devices',          category: 'stocks' },
  { symbol: 'INTC',   name: 'Intel Corporation',               category: 'stocks' },
  { symbol: 'NFLX',   name: 'Netflix Inc.',                    category: 'stocks' },
  { symbol: 'DIS',    name: 'The Walt Disney Company',         category: 'stocks' },
  { symbol: 'PYPL',   name: 'PayPal Holdings Inc.',            category: 'stocks' },
  { symbol: 'CRM',    name: 'Salesforce Inc.',                 category: 'stocks' },
  { symbol: 'COIN',   name: 'Coinbase Global Inc.',            category: 'stocks' },
  { symbol: 'MSTR',   name: 'MicroStrategy Inc.',              category: 'stocks' },
  { symbol: 'BAC',    name: 'Bank of America Corporation',     category: 'stocks' },
  { symbol: 'GS',     name: 'Goldman Sachs Group Inc.',        category: 'stocks' },
  { symbol: 'MS',     name: 'Morgan Stanley',                  category: 'stocks' },
  // ─── Aktien – EU / DE ────────────────────────────────────────────────────
  { symbol: 'SAP',    name: 'SAP SE',                          category: 'stocks' },
  { symbol: 'SIE',    name: 'Siemens AG',                      category: 'stocks' },
  { symbol: 'BMW',    name: 'Bayerische Motoren Werke AG',     category: 'stocks' },
  { symbol: 'VOW3',   name: 'Volkswagen AG Vz.',               category: 'stocks' },
  { symbol: 'MBG',    name: 'Mercedes-Benz Group AG',          category: 'stocks' },
  { symbol: 'ALV',    name: 'Allianz SE',                      category: 'stocks' },
  { symbol: 'BAS',    name: 'BASF SE',                         category: 'stocks' },
  { symbol: 'MRK',    name: 'Merck KGaA',                      category: 'stocks' },
  { symbol: 'RWE',    name: 'RWE AG',                          category: 'stocks' },
  { symbol: 'NVS',    name: 'Novartis AG',                     category: 'stocks' },
  { symbol: 'ASML',   name: 'ASML Holding N.V.',               category: 'stocks' },
  { symbol: 'MC',     name: 'LVMH Moët Hennessy Louis Vuitton',category: 'stocks' },
  { symbol: 'TTE',    name: 'TotalEnergies SE',                category: 'stocks' },
  { symbol: 'SHELL',  name: 'Shell plc',                       category: 'stocks' },
  { symbol: 'BP',     name: 'BP plc',                          category: 'stocks' },
  { symbol: 'HSBA',   name: 'HSBC Holdings plc',               category: 'stocks' },
  { symbol: 'RIO',    name: 'Rio Tinto Group',                 category: 'stocks' },
  { symbol: 'GSK',    name: 'GSK plc',                         category: 'stocks' },
]

export function searchAssets(query: string, limit = 15): AssetEntry[] {
  if (!query.trim()) return []
  const q = query.toLowerCase()
  const scored = ASSET_DATABASE.map(a => {
    const sym = a.symbol.toLowerCase()
    const nm  = a.name.toLowerCase()
    if (sym === q) return { a, score: 100 }
    if (sym.startsWith(q)) return { a, score: 90 }
    if (nm.startsWith(q)) return { a, score: 80 }
    if (sym.includes(q)) return { a, score: 70 }
    if (nm.includes(q)) return { a, score: 60 }
    return { a, score: 0 }
  }).filter(r => r.score > 0)
  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, limit).map(r => r.a)
}
