export interface ChangelogEntry {
  version: string
  date: string
  features?: string[]
  fixes?: string[]
}

// Auto-generated by scripts/release.mjs — extracted from git commit messages.
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.3.28',
    date: '2026-05-15',
    fixes: [
      'Fix QA bugs — streaming error, account validation, summarization timing, speech cleanup, duplicate detection',
    ],
  },
]

export function getCurrentChangelog(): ChangelogEntry {
  return CHANGELOG[0]
}
