export interface ChangelogEntry {
  version: string
  date: string
  features?: string[]
  fixes?: string[]
}

// Auto-generated by scripts/release.mjs — extracted from git commit messages.
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.3.65',
    date: '2026-05-18',
    fixes: [
      'Neutrales Schwarz statt Blau-Grau — kein Farbstich',
    ],
  },
]

export function getCurrentChangelog(): ChangelogEntry {
  return CHANGELOG[0]
}
