export interface ChangelogEntry {
  version: string
  date: string
  features?: string[]
  fixes?: string[]
}

// Auto-generated by scripts/release.mjs — extracted from git commit messages.
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.3.38',
    date: '2026-05-16',
    fixes: [
      'Fix calendar time parsing + add manual refresh button',
    ],
  },
]

export function getCurrentChangelog(): ChangelogEntry {
  return CHANGELOG[0]
}
