#!/usr/bin/env node
// Bumps patch version, auto-generates changelog from git commits, commits & pushes.
// Usage: npm run release
import { readFileSync, writeFileSync } from 'fs'
import { execSync } from 'child_process'

// ── 1. Bump version ────────────────────────────────────────────────────────────
const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
const [major, minor, patch] = pkg.version.split('.').map(Number)
const newVersion = `${major}.${minor}.${patch + 1}`
pkg.version = newVersion
writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n')
console.log(`✓ package.json: ${major}.${minor}.${patch} → ${newVersion}`)

// ── 2. Auto-generate changelog from git commits since last release ─────────────
function getCommitsSinceLastRelease() {
  try {
    const log = execSync('git log --oneline --no-merges -50', { encoding: 'utf8' })
    const lines = log.split('\n').filter(Boolean)
    const lastReleaseIdx = lines.findIndex(l => l.includes('chore: release'))
    const relevant = lastReleaseIdx > 0 ? lines.slice(0, lastReleaseIdx) : lines.slice(0, 15)
    return relevant
  } catch {
    return []
  }
}

function parseCommit(line) {
  const m = line.match(/^[a-f0-9]+ (feat|fix)(?:\([^)]+\))?:\s*(.+)/)
  if (!m) return null
  return { type: m[1], msg: m[2].trim() }
}

const commits = getCommitsSinceLastRelease()
const features = []
const fixes = []
for (const line of commits) {
  const parsed = parseCommit(line)
  if (!parsed) continue
  if (parsed.type === 'feat') features.push(parsed.msg)
  else if (parsed.type === 'fix') fixes.push(parsed.msg)
}

// ── 3. Update changelog.ts ──────────────────────────────────────────────────
const today = new Date()
const dateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`

const escape = s => s.replace(/'/g, "\\'")
const featuresStr = features.length
  ? `    features: [\n${features.map(f => `      '${escape(f)}',`).join('\n')}\n    ],\n`
  : ''
const fixesStr = fixes.length
  ? `    fixes: [\n${fixes.map(f => `      '${escape(f)}',`).join('\n')}\n    ],\n`
  : ''

const changelogContent = `export interface ChangelogEntry {
  version: string
  date: string
  features?: string[]
  fixes?: string[]
}

// Auto-generated by scripts/release.mjs — extracted from git commit messages.
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '${newVersion}',
    date: '${dateStr}',
${featuresStr}${fixesStr}  },
]

export function getCurrentChangelog(): ChangelogEntry {
  return CHANGELOG[0]
}
`

writeFileSync('src/lib/changelog.ts', changelogContent)
console.log(`✓ changelog.ts: ${features.length} features, ${fixes.length} fixes (auto from git)`)

// ── 4. Commit & push ──────────────────────────────────────────────────────────
execSync('git add package.json src/lib/changelog.ts', { stdio: 'inherit' })
execSync(`git commit -m "chore: release v${newVersion}"`, { stdio: 'inherit' })
// Pull rebase first to avoid fast-forward failures when other commits landed while Action ran
try {
  execSync('git pull --rebase origin main', { stdio: 'inherit' })
} catch {
  // If rebase fails, continue — push will surface the real error
}
execSync('git push origin main', { stdio: 'inherit' })
console.log(`\n✓ Released v${newVersion} — Vercel deploying…`)
